apiVersion: 1
groups:
    - orgId: 1
      name: 1m-group
      folder: Alert Rules
      interval: 1m
      rules:
        - uid: demykhzytyh34c
          title: Provision Alert - Request Rate
          condition: C
          data:
            - refId: A
              relativeTimeRange:
                from: 600
                to: 0
              datasourceUid: prometheus
              model:
                editorMode: code
                expr: rate(fastapi_requests_total{}[3m])
                instant: true
                intervalMs: 1000
                legendFormat: __auto
                maxDataPoints: 43200
                range: false
                refId: A
            - refId: C
              datasourceUid: __expr__
              model:
                conditions:
                    - evaluator:
                        params:
                            - 0.2
                        type: gt
                      operator:
                        type: and
                      query:
                        params:
                            - C
                      reducer:
                        params: []
                        type: last
                      type: query
                datasource:
                    type: __expr__
                    uid: __expr__
                expression: A
                intervalMs: 1000
                maxDataPoints: 43200
                refId: C
                type: threshold
          noDataState: NoData
          execErrState: Error
          for: 3m
          keepFiringFor: 3m
          annotations:
            Note: '{{$labels.app_name}} {{ $labels.path }}'
            description: Request Rate >= 0.2 req/s
            summary: Request Rate Alert
          labels: {}
          isPaused: false
          notification_settings:
            receiver: grafana-default-email
    # - orgId: 1
    #   name: 30s-group
    #   folder: Alert Rules
    #   interval: 30s
    #   rules:
    #     - uid: aenhy1ic14nb4e
    #       title: Container Memory Alert
    #       condition: C
    #       data:
    #         - refId: A
    #           relativeTimeRange:
    #             from: 600
    #             to: 0
    #           datasourceUid: prometheus
    #           model:
    #             editorMode: code
    #             expr: sum(container_memory_usage_bytes{container_label_com_docker_compose_project="devopsdays-taipei-2025-observability-bootcamp"}) by (name)
    #             instant: true
    #             intervalMs: 1000
    #             legendFormat: __auto
    #             maxDataPoints: 43200
    #             range: false
    #             refId: A
    #         - refId: C
    #           datasourceUid: __expr__
    #           model:
    #             conditions:
    #                 - evaluator:
    #                     params:
    #                         - 1e+08
    #                     type: gt
    #                   operator:
    #                     type: and
    #                   query:
    #                     params:
    #                         - C
    #                   reducer:
    #                     params: []
    #                     type: last
    #                   type: query
    #             datasource:
    #                 type: __expr__
    #                 uid: __expr__
    #             expression: A
    #             intervalMs: 1000
    #             maxDataPoints: 43200
    #             refId: C
    #             type: threshold
    #       noDataState: NoData
    #       execErrState: Error
    #       for: 1m
    #       keepFiringFor: 3m
    #       annotations:
    #         dashboard: http://localhost:3000/d/cadvisor-exporter/cadvisor-exporter?orgId=1&from=now-6h&to=now&timezone=browser&var-host=$__all&var-container={{ $labels.name }}
    #       labels: {}
    #       isPaused: false
    #       notification_settings:
    #         receiver: webhook
