spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  cache:
    type: redis
  # https://stackoverflow.com/a/79180709
  data:
    redis:
      host: localhost
      port: 6379
